### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `typos --format brief`

### CODE REVIEW

**Review by alokedesai — APPROVED** [review]
<3 Fixing typos is always appreciated!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by kianmeng** [comment]
@alokedesai How about adding `typos` to CI pipeline?

**Comment by alokedesai** [comment]
@kianmeng I'd be open to that, feel free to send a PR! The one thing I'd want to be conscious of is avoiding false positives, so it may make the most sense to not that step be blocking

**Pull request merged**
