### PR TITLE
(feat) add workflows for nx

### PR DESCRIPTION
**Pull request by mandarini**

### CODE REVIEW

**Review by ianhodge — APPROVED** [review]
Thank you so much for contributing to the workflows repo!

**Review by alokedesai — APPROVED** [review]
Thank you so much for contributing!! Much appreciated, this will go a long way in making sure this feature is useful for all users of Warp 🚀

**Comment by elviskahoro** [comment]
@mandarini are you in the Discord? If so what's your username, so I can add the contributor role?

**Comment by mandarini** [comment]
@elviskahoro yes! :) It's `pakotinia` :)

**Pull request merged**
