### PR TITLE
Add openfortivpn spec

### PR DESCRIPTION
**Pull request by rafalpetryka**
Simple workflow to connect via openfortivpn with one time password (token). Unfortunately this command requires sudo. But it works for me! ;)

### CODE REVIEW

**Comment by elviskahoro** [comment]
@rafalpetryka are you in our discord? if so what's your username so I can add the contributor role?

**Comment by rafalpetryka** [comment]
@elviskahoro just joined as rafalpetryka#7035

**Review by alokedesai — APPROVED** [review]
Thank you so much for contributing!

**Comment by elviskahoro** [comment]
@rafalpetryka just got you added! thanks again!

**Pull request merged**
