### PR TITLE
Workflows for Flutter

### PR DESCRIPTION
**Pull request by BirjuVachhani**

### CODE REVIEW

**Review by alokedesai — APPROVED** [review]
These look great! Thank you so much for contributing and improving the product experience in Warp <3

**Comment by elviskahoro** [comment]
@BirjuVachhani are you in the Discord? If so what's your username, so I can add the contributor role?

**Comment by BirjuVachhani** [comment]
@elviskahoro Sure. My username is `birjuvachhani`

**Comment by BirjuVachhani** [comment]
Just joined

**Pull request merged**
