### PR TITLE
fix: typo in "Create Next.js App"

### PR DESCRIPTION
**Pull request by styfle**
## Discord username (optional) please include so we can attribute you with our Contributor role (like so elvis#4747)

`styfle#3692`

## Description of changes (updated or new workflows)

Fixes a typo since Next.js uses lowercase "js". Also "App" should be uppercase.

See the official docs https://nextjs.org/docs/app/api-reference/create-next-app

### CODE REVIEW

**Comment by styfle** [comment]
@elviskahoro Anything else I need to do here?

**Review by elviskahoro — APPROVED** [review]

**Comment by styfle** [comment]
@elviskahoro Looks like the latest merge broke CI 🤔

**Comment by elviskahoro** [comment]
> Author

Nope! Gonna debug on Monday!

**Comment by styfle** [comment]
@elviskahoro CI passed but it didn't automatically merge so I tried clicking update again

**Comment by elviskahoro** [comment]
@styfle re-running. let's see how it goes.

**Pull request merged**
